### PR TITLE
omit hidden files from ctags calculations

### PR DESCRIPTION
**Pull request by nerdypepper**
files such as `.eslint.rc` and `.gitignore` were being omitted from the index.

### CODE REVIEW

**Comment by ggordonhall** [comment]
We use a similar walker [here](https://github.com/BloopAI/bloop/blob/f6fce1d251985880c6258ae8f3dcf27f13541fb5/server/bleep/src/ctags.rs#L40) and [here](https://github.com/BloopAI/bloop/blob/f6fce1d251985880c6258ae8f3dcf27f13541fb5/server/bleep/src/language.rs#L22). Can you think of situations where we'd want to calculate language and symbols for hidden files?

**Comment by nerdypepper** [comment]
>We use a similar walker [here](https://github.com/BloopAI/bloop/blob/f6fce1d251985880c6258ae8f3dcf27f13541fb5/server/bleep/src/ctags.rs#L40) and [here](https://github.com/BloopAI/bloop/blob/f6fce1d251985880c6258ae8f3dcf27f13541fb5/server/bleep/src/language.rs#L22). Can you think of situations where we'd want to calculate language and symbols for hidden files?

good catch, i can see language being useful (`.eslintrc.json` can be detected as json), we can skip hidden files for ctags calculations.

**Comment by rsdy** [comment]
What's blocking the merge of this?

**Comment by nerdypepper** [comment]
my negligence. ill enable hidden files for `get_language_info` and merge this in.

**Comment by nerdypepper** [comment]
so this changeset is already on `main`, i propose that we disable ctags for hidden files however; updating this PR in accordance.

**Pull request merged**
