### PR TITLE
Store incomplete conversations

### PR DESCRIPTION
**Pull request by calyptobai**
Now, conversations will persist in the database even if they do not properly complete. Failed conversations are still not persisted with this change, intentionally.

Closes BLO-1364

### CODE REVIEW

**Review by ggordonhall — CHANGES_REQUESTED** [review]
We also want to add any incomplete, but cancelled, answers to the conversation history. So that the user could then follow up with a question like `list the other ones?` (referring to the partial answer in the previous step).

**Comment by calyptobai** [comment]
> We also want to add any incomplete, but cancelled, answers to the conversation history. So that the user could then follow up with a question like `list the other ones?` (referring to the partial answer in the previous step).

To clarify, this is the intended behaviour of this change. The original PR wording is confusing, it should say "are cancelled" instead of "do not properly complete".

We add _cancelled_ answers, but **not** answers that _failed_ to complete.

**Comment by ggordonhall** [comment]
> We add _cancelled_ answers, but **not** answers that _failed_ to complete.

I noticed that if I let bloop start generating an answer, then hit the button to cancel generation, the partial answer _does not_ end up in the history for subsequent questions.

**Comment by calyptobai** [comment]
> I noticed that if I let bloop start generating an answer, then hit the button to cancel generation, the partial answer does not end up in the history for subsequent questions.

Ah I see the issue. The response was being stored on the back-end but we didn't display it properly on the front-end due to a missing conclusion. I've introduced some canned conclusions here, selected randomly from:

```
"The article wasn't completed. See what's available",
"Your article stopped before completion. Check out the available content",
"The content stopped generating early. Review the initial response"
```

**Review by ggordonhall — APPROVED** [review]

**Pull request merged**
