### PR TITLE
Add simplified Chinese support.

### PR DESCRIPTION
**Pull request by BB-fat**
#815

### CODE REVIEW

**Review by anastasiya1155 — APPROVED** [review]

**Comment by anastasiya1155** [comment]
Can you update LocaleType in client/src/types/general.ts:310?

**Comment by BB-fat** [comment]
> Can you update LocaleType in client/src/types/general.ts:310?

Okey.

**Comment by BB-fat** [comment]
@anastasiya1155 It's done.

**Comment by anastasiya1155** [comment]
Perfect! Thanks for your contribution!

**Pull request merged**
