### PR TITLE
Make search input wider

### PR DESCRIPTION
**Pull request by anastasiya1155**
Now search input will take more space in the header so that long queries fit into it better

### CODE REVIEW

**Comment by anastasiya1155** [comment]
@stunningpixels can you check it and confirm that it's better now?

**Review by ipauler — APPROVED** [review]

**Comment by stunningpixels** [comment]
Screenshot 2023-01-10 at 09 51 04

Can we standardise max widths pls. Other than that, looks good to me.

**Comment by anastasiya1155** [comment]
> Screenshot 2023-01-10 at 09 51 04
> 
> Can we standardise max widths pls. Other than that, looks good to me.

it's not as simple as it may seem. The main body has a left sidebar that can be collapsed when it shows filters, while the navbar has icons on the left and on the right, which makes input positioning a bit hard. I will have to spend a bit more time thinking about the correct position.

**Comment by stunningpixels** [comment]
Ok let's merge

**Pull request merged**
