### PR TITLE
Upvote animation

### PR DESCRIPTION
**Pull request by anastasiya1155**
When user clicks on upvote button show animation exported from Rive

### CODE REVIEW

**Review by ipauler — DISMISSED** [review]

**Comment by stunningpixels** [comment]
It looks good but I think we should do downvote too?

**Comment by anastasiya1155** [comment]
> It looks good but I think we should do downvote too?

Do you want the same animation, but upside down or should I ping Vasil to create a new one?

**Comment by anastasiya1155** [comment]
@stunningpixels please test and approve this one

**Comment by anastasiya1155** [comment]
https://user-images.githubusercontent.com/35258279/214545217-938ffe35-c26d-444c-8ce9-674804bdfbd9.mov

@stunningpixels

**Comment by anastasiya1155** [comment]
Superseded by https://github.com/BloopAI/bloop/pull/159

**Pull request closed without merging**
