### PR TITLE
Scroll full code file to first line in its preview

### PR DESCRIPTION
**Pull request by anastasiya1155**

### CODE REVIEW

**Review by ipauler — DISMISSED** [review]

**Comment by stunningpixels** [comment]
Highlights the wrong place

https://user-images.githubusercontent.com/7957964/212900970-70df097a-1086-4d28-83b2-ac66355a4c0d.mp4

**Comment by anastasiya1155** [comment]
> Highlights the wrong place

it highlights the same line that the preview starts, it's just happens to be an empty line

**Comment by stunningpixels** [comment]
Can we highlight all code in search result, when file opens?

**Comment by anastasiya1155** [comment]
> Can we highlight all code in search result, when file opens?

I think yes, will do it tomorrow

**Comment by anastasiya1155** [comment]
@stunningpixels ready for another review

**Comment by anastasiya1155** [comment]
https://user-images.githubusercontent.com/35258279/214550994-6024a3bb-bf2e-439a-bca2-42ab91d98c8e.mov

@stunningpixels

**Pull request merged**
